export enum FontSizes {
	axisLabelsSmall = "10px",
	axisLabelsMedium = "11px",
	xxSmall = "0.8em",
	xSmall = "0.9em",
	small = "1em",
	medium = "1.1em",
	xLarge = "1.3em",
	xxLarge = "0.95rem",
	pageTitle = "20px",
	cardTitle = "12px",
	standardXSmall = "0.6rem",
	standardSmall = "0.7rem",
	standardMedium = "0.85rem",
	standardLarge = "1rem",
	titleMedium = "1.18rem",
	titleLarge = "1.35rem",
	titleXLarge = "1.73rem",
	titleXXLarge = "2.32rem",
}
